apiVersion: v1
kind: Service
metadata:
  name: service-postgres
spec:
   type: NodePort
   ports:
   - targetPort: 5432
     protocol: TCP
     port: 5432
     nodePort: 30009
   selector:
    tier: dbd